### ISSUE TITLE
JWE handling does not prepend the algorithm to the salt

### ISSUE THREAD

**Issue by lagebaue** [teifip/node-webtokens#3]
As stated in "4.8.  Key Encryption with PBES2" in https://tools.ietf.org/html/rfc7518#appendix-C 

>    the salt parameter MUST be computed from the "p2s" (PBES2 salt input) Header Parameter value
>    and the "alg" (algorithm) Header Parameter value"

You might want to consider testing against data generated by a different implementation like this
https://github.com/cisco/node-jose/blob/master/test/jwe/jwe-test.js

**Comment by teifip** [comment]
@lagebaue - Thanks for reporting the issue. `p2s` was incorrectly set equal to the salt rather than equal to the salt input. Now fixed and published in NPM as `v1.0.1`.
