### ISSUE TITLE
unnecessary dependency "jws"

### ISSUE THREAD

**Issue by lagebaue** [teifip/node-webtokens#4]
In one of the cleanup commits `jws` was added to the `dependencies` list but probably should be in `devDependencies` as it is only used by one of the tests. At the moment everyone who uses this library also installs `jws`.

https://github.com/teifip/node-webtokens/commit/df31ad6e25b61d47aab3df534e8ba1813a0df15a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R28

**Comment by teifip** [comment]
Shame on me! Thanks for reporting. And thanks for your patience. Now fixed in `v1.0.3`.
