### ISSUE TITLE
TypeError: Key length must be at least 32 bytes

### ISSUE THREAD

**Issue by hansiemithun** [teifip/node-webtokens#5]
For the combination algorithm and encryption below:

jweAlg =>  A256KW
jweEnc =>  A128CBC-HS256

Getting error as: `TypeError: Key length must be at least 32 bytes`

I am using callbacks as well, but still no luck :( 

What could be the reason?

**Comment by hansiemithun** [comment]
I figured out with multiple combinations, it is because of: `jweAlg: A256KW`. If it is not used, then this works fine.

**Comment by teifip** [comment]
@hansiemithun - Glad to hear to you solved the problem. Keep in mind that the 32-byte minimum key length is a requirement dictated by the A256KW key management algorithm. You can see these requirements in Table 2 of the README.
